# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b4ddf421adf43c33929b1b1fc08ec629d08e386775c883a3693562ab5dad73ff6c550e21413ff0927d261a818b36883a9d23e78d2236ea70411d88b2d6899b9

test:
  secret_key_base: 2c5f9757ae6ab99ccc5860ed1a1a72a36401e013f2577cb84123b308ab89bf6f348068e67bcb7f5ab3d82d39e9054d0e927ca1801f716ebddf3ad0cdce510202

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
